# Generated by Django 3.2.8 on 2021-10-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('datetime_added', models.DateTimeField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
